//! Loaded mode (feature `loaded`): plans compiled on the host into a blob, loaded at run time
//! and run by an interpreter over the firmware's node library.
//!
//! - The **node library** ([`Library`]) is generated by `daedalus_mcu_build::library` from the
//!   nodes the firmware includes: per node its port types and a type-erased `run` adapter over
//!   the node's `run` glue. Its hash covers the node interfaces (ids, ports, types, fire mode).
//! - A **plan blob** (see [`FORMAT_VERSION`] and docs/mcu.md) names library entries, edges with
//!   their queue capacity and overflow policy, constants and parameters and host ports.
//! - The [`Interpreter`] validates a blob against its library and its fixed RAM arena, lays the
//!   plan out in the arena (tables, queues, node state, constants) and runs it; `tick` never
//!   allocates. Port values are `Copy`; node states have no drop glue.

mod interp;
mod plan;

use core::mem::{align_of, needs_drop, size_of};

use crate::{Ctx, McuType, NodeError, NodeState, ScalarKind, for_each_scalar};

pub use interp::Interpreter;

/// Blob format version (the byte after the `DMCU` magic).
pub const FORMAT_VERSION: u8 = 1;
/// The first bytes of every plan blob.
pub const MAGIC: [u8; 4] = *b"DMCU";
/// Most inputs or outputs a library node may have.
pub const MAX_PORTS: usize = 8;

/// A node library: the nodes a firmware can run in loaded mode, generated by
/// `daedalus_mcu_build::library`.
pub struct Library {
    /// Hash of the node interfaces; a plan names the library it was compiled for.
    pub hash: u64,
    /// Port types that are not scalars, type ids `SCALAR_TYPES..` in order.
    pub types: &'static [TypeInfo],
    pub nodes: &'static [NodeEntry],
}

/// Type ids below this are [`ScalarKind`]s (`kind as u16`); library types follow.
pub const SCALAR_TYPES: u16 = ScalarKind::ALL.len() as u16;

impl Library {
    /// The type with id `ty`.
    pub fn ty(&self, ty: u16) -> Option<TypeInfo> {
        macro_rules! scalars {
            ($($kind:ident: $ty:ty),* $(,)?) => { [$(TypeInfo::of::<$ty>()),*] };
        }
        const SCALARS: [TypeInfo; SCALAR_TYPES as usize] = for_each_scalar!(scalars);
        match SCALARS.get(usize::from(ty)) {
            Some(info) => Some(*info),
            None => self.types.get(usize::from(ty - SCALAR_TYPES)).copied(),
        }
    }
}

/// The scalar kind of type id `ty`, if it is one.
pub(crate) fn scalar_kind(ty: u16) -> Option<ScalarKind> {
    u8::try_from(ty).ok().and_then(ScalarKind::from_u8)
}

/// A port type: [`name_hash`](crate::name_hash) of its [`McuType::KEY`], size and alignment.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct TypeInfo {
    pub key: u32,
    pub size: u16,
    pub align: u8,
}

impl TypeInfo {
    pub const fn of<T: McuType + Copy>() -> Self {
        assert!(size_of::<T>() <= u16::MAX as usize && align_of::<T>() <= 8);
        Self {
            key: crate::name_hash(T::KEY),
            size: size_of::<T>() as u16,
            align: align_of::<T>() as u8,
        }
    }
}

/// One library node.
pub struct NodeEntry {
    pub inputs: &'static [InputEntry],
    /// Output type ids.
    pub outputs: &'static [u16],
    pub state: StateEntry,
    pub run: RunFn,
}

#[derive(Clone, Copy, Debug)]
pub struct InputEntry {
    pub ty: u16,
    /// An `Option` input: never blocks the node.
    pub optional: bool,
}

/// A node's state slot.
#[derive(Clone, Copy, Debug)]
pub struct StateEntry {
    pub size: u16,
    pub align: u8,
    /// Writes [`NodeState::INIT`] to the slot.
    pub init: unsafe fn(*mut u8),
}

impl StateEntry {
    pub const fn of<S: NodeState>() -> Self {
        assert!(
            !needs_drop::<S>(),
            "loaded-mode node states have no drop glue"
        );
        assert!(size_of::<S>() <= u16::MAX as usize && align_of::<S>() <= 8);
        Self {
            size: size_of::<S>() as u16,
            align: align_of::<S>() as u8,
            init: init_state::<S>,
        }
    }
}

/// # Safety
/// `slot` is valid and aligned for an `S`.
unsafe fn init_state<S: NodeState>(slot: *mut u8) {
    // SAFETY: the caller's contract.
    unsafe { slot.cast::<S>().write(S::INIT) }
}

/// A type-erased node call: `state` is the node's state slot; `io` holds pointers to the input
/// values (null for an absent optional input) and to output slots.
pub type RunFn = unsafe fn(state: *mut u8, ctx: &Ctx, io: &mut Io) -> Result<(), NodeError>;

/// Port values of one node call, used by the generated `run` adapters.
pub struct Io {
    inputs: [*const u8; MAX_PORTS],
    outputs: [*mut u8; MAX_PORTS],
    produced: u8,
}

impl Io {
    const fn new() -> Self {
        Self {
            inputs: [core::ptr::null(); MAX_PORTS],
            outputs: [core::ptr::null_mut(); MAX_PORTS],
            produced: 0,
        }
    }

    /// Required input `k`.
    ///
    /// # Safety
    /// Input `k` holds a `T` (the interpreter checks the plan's types against the library).
    #[inline]
    pub unsafe fn input<T: Copy>(&self, k: usize) -> T {
        // SAFETY: the caller's contract.
        unsafe { self.inputs[k].cast::<T>().read_unaligned() }
    }

    /// Optional input `k`.
    ///
    /// # Safety
    /// Input `k` is null or holds a `T`.
    #[inline]
    pub unsafe fn input_opt<T: Copy>(&self, k: usize) -> Option<T> {
        let ptr = self.inputs[k];
        // SAFETY: the caller's contract.
        (!ptr.is_null()).then(|| unsafe { ptr.cast::<T>().read_unaligned() })
    }

    /// Output `k` (`None` produces nothing).
    ///
    /// # Safety
    /// Output `k`'s slot holds a `T`.
    #[inline]
    pub unsafe fn output<T: Copy>(&mut self, k: usize, value: Option<T>) {
        if let Some(value) = value {
            // SAFETY: the caller's contract.
            unsafe { self.outputs[k].cast::<T>().write_unaligned(value) };
            self.produced |= 1 << k;
        }
    }
}

/// A rejected plan blob; the running plan (if any) stays loaded.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
#[non_exhaustive]
pub enum LoadError {
    /// Not a plan blob, truncated, or trailing bytes.
    Malformed,
    /// A blob format version this firmware does not read.
    Version { found: u8 },
    /// Compiled for another node library.
    Library { expected: u64, found: u64 },
    /// A node names no library entry, or its input count differs.
    Node { node: u16 },
    /// A required input has no source, or a constant has another type than the input.
    Input { node: u16, input: u8 },
    /// An edge's producer does not exist or does not run before its consumer, or its queue
    /// shape is invalid.
    Edge { edge: u16 },
    /// An edge's producer and consumer types differ and do not widen.
    Type { edge: u16 },
    /// A parameter's value, range or type is invalid.
    Param { param: u16 },
    /// A host port has an unknown type.
    Port { port: u16 },
    /// The plan needs `needed` bytes of arena.
    Arena { needed: u32 },
}

impl From<crate::wire::WireError> for LoadError {
    fn from(_: crate::wire::WireError) -> Self {
        Self::Malformed
    }
}
