use super::{
    InstallFn, PLUGIN_ABI_SYMBOL, PLUGIN_ABI_VERSION, PLUGIN_DESCRIPTOR_SYMBOL, PluginDescriptor,
    PluginInfo, PluginSchema, StrSink, StrView,
};
use crate::runtime::plugins::PluginRegistry;
use daedalus_ffi_host::core::BackendKind;
use libloading::Library;
use std::collections::BTreeMap;
use std::ffi::c_void;
use std::path::{Path, PathBuf};
use thiserror::Error;

/// Why a plugin cannot use the Rust-ABI install path of this host (see the [module docs](super)).
#[derive(Clone, Debug, Error, PartialEq, Eq)]
#[non_exhaustive]
pub enum RustAbiMismatch {
    #[error("plugin was built against Daedalus {found}, host uses Daedalus {expected}")]
    DaedalusVersion { expected: String, found: String },
    #[error("plugin was built with `{found}`, host was built with `{expected}`")]
    Rustc { expected: String, found: String },
    #[error("build fingerprint mismatch ({differences}); host `{expected}`, plugin `{found}`")]
    BuildFingerprint {
        expected: String,
        found: String,
        /// Human-readable list of the differing fingerprint segments.
        differences: String,
    },
}

/// Errors that can occur while loading or installing a dynamic plugin library.
#[derive(Debug, Error)]
#[non_exhaustive]
pub enum PluginLibraryError {
    #[error("failed to load plugin library `{}`: {source}", path.display())]
    Load {
        path: PathBuf,
        #[source]
        source: libloading::Error,
    },
    #[error("plugin library `{}` does not export symbol `{symbol}`", path.display())]
    MissingSymbol { path: PathBuf, symbol: &'static str },
    #[error("plugin ABI mismatch: host expects {expected}, plugin reports {found}")]
    AbiMismatch { expected: u32, found: u32 },
    #[error("plugin info field `{field}` is null or not valid UTF-8")]
    InvalidInfo { field: &'static str },
    #[error("plugin `{plugin}` did not provide a valid schema: {message}")]
    Schema { plugin: String, message: String },
    /// The plugin loaded and its schema is readable, but it cannot be installed into this host.
    #[error("plugin `{plugin}` cannot be installed into this host: {mismatch}")]
    Incompatible {
        plugin: String,
        #[source]
        mismatch: RustAbiMismatch,
    },
    #[error("plugin failed to register boundary contracts: {message}")]
    BoundaryContractsFailed { message: String },
    #[error("plugin registration failed: {message}")]
    RegisterFailed { message: String },
}

type AbiFn = unsafe extern "C" fn() -> u32;
type DescriptorFn = unsafe extern "C" fn() -> PluginDescriptor;

/// A loaded native Rust plugin library (built with [`export_plugin!`](crate::export_plugin)).
///
/// The underlying library is leaked and never unloaded; see the [module docs](super).
pub struct PluginLibrary {
    path: PathBuf,
    descriptor: PluginDescriptor,
    schema: PluginSchema,
    rust_abi: Result<(), RustAbiMismatch>,
}

impl std::fmt::Debug for PluginLibrary {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let info = &self.descriptor.info;
        f.debug_struct("PluginLibrary")
            .field("path", &self.path)
            .field("plugin_name", &info.plugin_name.as_str())
            .field("plugin_version", &info.plugin_version.as_str())
            .field("rust_abi", &self.rust_abi)
            .finish()
    }
}

impl PluginLibrary {
    /// Load a plugin library and read its descriptor and schema.
    ///
    /// Uses only C-ABI calls: checks the ABI version, validates the [`PluginInfo`] strings, and
    /// fetches and validates the plugin's [`PluginSchema`]. A plugin built with another
    /// toolchain, Daedalus version or feature set still loads, so it can be inspected;
    /// [`rust_abi`](Self::rust_abi) reports whether [`install_into`](Self::install_into) will
    /// accept it. The library stays loaded for the rest of the process, even when loading fails
    /// after it was opened.
    ///
    /// # Safety
    /// Loading a library runs its initialisers, and the exported symbols are trusted to have
    /// the signatures generated by `export_plugin!`. The caller must ensure `path` points to a
    /// trusted Daedalus plugin.
    pub unsafe fn load(path: impl AsRef<Path>) -> Result<Self, PluginLibraryError> {
        let path = path.as_ref().to_path_buf();
        // Safety: forwarded from the caller.
        let library =
            unsafe { Library::new(&path) }.map_err(|source| PluginLibraryError::Load {
                path: path.clone(),
                source,
            })?;
        // Never unload: registered handlers and static data point into the library.
        let library: &'static Library = Box::leak(Box::new(library));

        // Safety (symbol lookups and calls): signatures are defined by `export_plugin!`; the
        // descriptor symbol is only called once the ABI version pins its shape.
        let abi: AbiFn = unsafe { symbol(library, &path, PLUGIN_ABI_SYMBOL) }?;
        check_abi_version(unsafe { abi() }, PLUGIN_ABI_VERSION)?;
        let descriptor: DescriptorFn = unsafe { symbol(library, &path, PLUGIN_DESCRIPTOR_SYMBOL) }?;
        // Safety: the descriptor comes from a plugin with a matching ABI version.
        unsafe { Self::from_descriptor(path, descriptor()) }
    }

    /// # Safety
    /// `descriptor` must come from a plugin with ABI version [`PLUGIN_ABI_VERSION`].
    unsafe fn from_descriptor(
        path: PathBuf,
        descriptor: PluginDescriptor,
    ) -> Result<Self, PluginLibraryError> {
        let info = &descriptor.info;
        let plugin = info_field(info.plugin_name, "plugin_name")?.to_string();
        info_field(info.plugin_version, "plugin_version")?;
        info_field(info.daedalus_version, "daedalus_version")?;
        info_field(info.rustc_version, "rustc_version")?;
        info_field(info.build_fingerprint, "build_fingerprint")?;

        let schema_error = |message: String| PluginLibraryError::Schema {
            plugin: plugin.clone(),
            message,
        };
        // Safety: `schema` only exchanges borrowed bytes through the C-ABI sink.
        let json = call(|sink| unsafe { (descriptor.schema)(sink) }).map_err(schema_error)?;
        let schema: PluginSchema =
            serde_json::from_str(&json).map_err(|err| schema_error(err.to_string()))?;
        schema
            .validate_backend_kind(BackendKind::Rust)
            .map_err(|err| schema_error(err.to_string()))?;
        Ok(Self {
            path,
            rust_abi: check_rust_abi(info),
            descriptor,
            schema,
        })
    }

    /// Install the plugin (boundary contracts first, then the plugin itself) into `registry`.
    ///
    /// Fails with [`PluginLibraryError::Incompatible`] without calling into the plugin when
    /// [`rust_abi`](Self::rust_abi) reports a mismatch.
    pub fn install_into(&self, registry: &mut PluginRegistry) -> Result<(), PluginLibraryError> {
        if let Err(mismatch) = &self.rust_abi {
            return Err(PluginLibraryError::Incompatible {
                plugin: self.schema.plugin.name.clone(),
                mismatch: mismatch.clone(),
            });
        }
        let install = |entry: InstallFn, registry: &mut PluginRegistry| {
            let registry = (registry as *mut PluginRegistry).cast::<c_void>();
            // Safety: `check_rust_abi` accepted the plugin; the registry pointer is exclusive
            // for the call and the sink outlives it.
            call(|sink| unsafe { entry(registry, sink) })
        };
        install(self.descriptor.register_boundary_contracts, registry)
            .map_err(|message| PluginLibraryError::BoundaryContractsFailed { message })?;
        install(self.descriptor.register, registry)
            .map(drop)
            .map_err(|message| PluginLibraryError::RegisterFailed { message })
    }

    /// Metadata reported by the plugin.
    pub fn info(&self) -> PluginInfo {
        self.descriptor.info
    }

    /// The plugin's manifest and node declarations, readable whatever built the plugin.
    pub fn schema(&self) -> &PluginSchema {
        &self.schema
    }

    /// Whether the plugin can be installed into this host through the Rust ABI.
    pub fn rust_abi(&self) -> Result<(), &RustAbiMismatch> {
        self.rust_abi.as_ref().copied()
    }

    /// Path the library was loaded from.
    pub fn path(&self) -> &Path {
        &self.path
    }
}

/// # Safety
/// `T` must be the function pointer type matching the exported symbol.
unsafe fn symbol<T: Copy>(
    library: &'static Library,
    path: &Path,
    name: &'static str,
) -> Result<T, PluginLibraryError> {
    // Safety: forwarded from the caller.
    unsafe { library.get::<T>(name.as_bytes()) }
        .map(|sym| *sym)
        .map_err(|_| PluginLibraryError::MissingSymbol {
            path: path.to_path_buf(),
            symbol: name,
        })
}

unsafe extern "C" fn write_string(ctx: *mut c_void, ptr: *const u8, len: usize) {
    if ctx.is_null() || ptr.is_null() {
        return;
    }
    // Safety: `ctx` is the `Option<String>` owned by `call`, and the plugin passes a valid
    // `(ptr, len)` byte slice for the duration of this call.
    let (slot, bytes) = unsafe {
        (
            &mut *ctx.cast::<Option<String>>(),
            std::slice::from_raw_parts(ptr, len),
        )
    };
    *slot = Some(String::from_utf8_lossy(bytes).into_owned());
}

/// Call a plugin entry point with a sink; return the string it wrote (empty if none) on
/// success, or its error message on failure.
fn call(entry: impl FnOnce(StrSink) -> bool) -> Result<String, String> {
    let mut written: Option<String> = None;
    let sink = StrSink {
        ctx: (&mut written as *mut Option<String>).cast(),
        write: Some(write_string),
    };
    match (entry(sink), written) {
        (true, written) => Ok(written.unwrap_or_default()),
        (false, Some(message)) => Err(message),
        (false, None) => Err("plugin reported failure without a message".to_string()),
    }
}

fn info_field(view: StrView, field: &'static str) -> Result<&'static str, PluginLibraryError> {
    view.as_str()
        .ok_or(PluginLibraryError::InvalidInfo { field })
}

fn check_abi_version(found: u32, expected: u32) -> Result<(), PluginLibraryError> {
    if found == expected {
        Ok(())
    } else {
        Err(PluginLibraryError::AbiMismatch { expected, found })
    }
}

/// Check whether a plugin with this metadata can be installed into this host through the Rust
/// ABI: its Daedalus version, rustc version and build fingerprint must match the host's.
pub fn check_rust_abi(info: &PluginInfo) -> Result<(), RustAbiMismatch> {
    check_rust_abi_against(info, &PluginInfo::for_plugin("host", "host"))
}

fn check_rust_abi_against(info: &PluginInfo, host: &PluginInfo) -> Result<(), RustAbiMismatch> {
    let pair = |f: fn(&PluginInfo) -> StrView| {
        let text = |info: &PluginInfo| f(info).as_str().unwrap_or_default().to_string();
        (text(host), text(info))
    };
    let (expected, found) = pair(|i| i.daedalus_version);
    if expected != found {
        return Err(RustAbiMismatch::DaedalusVersion { expected, found });
    }
    let (expected, found) = pair(|i| i.rustc_version);
    if expected != found {
        return Err(RustAbiMismatch::Rustc { expected, found });
    }
    let (expected, found) = pair(|i| i.build_fingerprint);
    if expected != found {
        return Err(RustAbiMismatch::BuildFingerprint {
            differences: super::describe_fingerprint_mismatch(&expected, &found),
            expected,
            found,
        });
    }
    Ok(())
}

/// Find plugin libraries (`.so`, `.dylib`, `.dll`) in `dirs`.
///
/// Directories that do not exist are skipped. When several directories contain a file with
/// the same name, the one from the earliest directory wins. The result is sorted by file name
/// so load order is deterministic.
pub fn discover_plugin_libraries<I, P>(dirs: I) -> std::io::Result<Vec<PathBuf>>
where
    I: IntoIterator<Item = P>,
    P: AsRef<Path>,
{
    let mut found: BTreeMap<std::ffi::OsString, PathBuf> = BTreeMap::new();
    for dir in dirs {
        let entries = match std::fs::read_dir(dir.as_ref()) {
            Ok(entries) => entries,
            Err(err) if err.kind() == std::io::ErrorKind::NotFound => continue,
            Err(err) => return Err(err),
        };
        for entry in entries {
            let path = entry?.path();
            let is_library = path
                .extension()
                .and_then(|ext| ext.to_str())
                .is_some_and(|ext| matches!(ext, "so" | "dylib" | "dll"));
            if !is_library || !path.is_file() {
                continue;
            }
            if let Some(name) = path.file_name() {
                found.entry(name.to_os_string()).or_insert(path);
            }
        }
    }
    Ok(found.into_values().collect())
}

#[cfg(test)]
mod tests;
