use super::{
    BOUNDARY_CONTRACTS_SYMBOL, PLUGIN_ABI_SYMBOL, PLUGIN_ABI_VERSION, PLUGIN_INFO_SYMBOL,
    PluginErrorSink, PluginInfo, REGISTER_SYMBOL, StrView,
};
use crate::runtime::plugins::PluginRegistry;
use libloading::Library;
use std::collections::BTreeMap;
use std::ffi::c_void;
use std::path::{Path, PathBuf};
use thiserror::Error;

/// Errors that can occur while loading or installing a dynamic plugin library.
#[derive(Debug, Error)]
#[non_exhaustive]
pub enum PluginLibraryError {
    #[error("failed to load plugin library `{}`: {source}", path.display())]
    Load {
        path: PathBuf,
        #[source]
        source: libloading::Error,
    },
    #[error("plugin library `{}` does not export symbol `{symbol}`", path.display())]
    MissingSymbol { path: PathBuf, symbol: &'static str },
    #[error("plugin ABI mismatch: host expects {expected}, plugin reports {found}")]
    AbiMismatch { expected: u32, found: u32 },
    #[error("plugin info field `{field}` is null or not valid UTF-8")]
    InvalidInfo { field: &'static str },
    #[error("plugin was built against Daedalus {found}, host uses Daedalus {expected}")]
    DaedalusVersionMismatch { expected: String, found: String },
    #[error("plugin was built with `{found}`, host was built with `{expected}`")]
    RustcVersionMismatch { expected: String, found: String },
    #[error(
        "plugin build fingerprint mismatch ({differences}); host `{expected}`, plugin `{found}`"
    )]
    BuildFingerprintMismatch {
        expected: String,
        found: String,
        /// Human-readable list of the differing fingerprint segments.
        differences: String,
    },
    #[error("plugin failed to register boundary contracts: {message}")]
    BoundaryContractsFailed { message: String },
    #[error("plugin registration failed: {message}")]
    RegisterFailed { message: String },
}

type AbiFn = unsafe extern "C" fn() -> u32;
type InfoFn = unsafe extern "C" fn() -> PluginInfo;
type InstallFn = unsafe extern "C" fn(*mut PluginRegistry, PluginErrorSink) -> bool;

/// A loaded native Rust plugin library (built with [`export_plugin!`](crate::export_plugin)).
///
/// The underlying library is leaked and never unloaded; see the [module docs](super).
pub struct PluginLibrary {
    path: PathBuf,
    info: PluginInfo,
    register: InstallFn,
    boundary_contracts: InstallFn,
}

impl std::fmt::Debug for PluginLibrary {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("PluginLibrary")
            .field("path", &self.path)
            .field("plugin_name", &self.info.plugin_name.as_str())
            .field("plugin_version", &self.info.plugin_version.as_str())
            .finish()
    }
}

impl PluginLibrary {
    /// Load a plugin library and verify it is compatible with this host.
    ///
    /// Checks, in order and using only C-safe calls: the ABI version, then the Daedalus
    /// version, rustc version and build fingerprint reported by `daedalus_plugin_info`
    /// (see [`check_plugin_info`]). Nothing is registered until
    /// [`install_into`](Self::install_into) is called. The library stays loaded for the rest of
    /// the process, even when loading fails after it was opened.
    ///
    /// # Safety
    /// Loading a library runs its initialisers, and the exported symbols are trusted to have
    /// the signatures generated by `export_plugin!`. The caller must ensure `path` points to a
    /// trusted Daedalus plugin built from the same dependency graph, toolchain and Daedalus
    /// feature set as the host (the checks catch common mismatches but cannot prove layout
    /// compatibility), and that host and plugin share the system allocator.
    pub unsafe fn load(path: impl AsRef<Path>) -> Result<Self, PluginLibraryError> {
        let path = path.as_ref().to_path_buf();
        // Safety: forwarded from the caller.
        let library =
            unsafe { Library::new(&path) }.map_err(|source| PluginLibraryError::Load {
                path: path.clone(),
                source,
            })?;
        // Never unload: registered handlers and static data point into the library.
        let library: &'static Library = Box::leak(Box::new(library));

        // Safety (all symbol lookups/calls below): signatures are defined by `export_plugin!`,
        // and the ABI version is checked before any symbol whose shape could have changed.
        let abi: AbiFn = unsafe { symbol(library, &path, PLUGIN_ABI_SYMBOL) }?;
        check_abi_version(unsafe { abi() })?;
        let info_fn: InfoFn = unsafe { symbol(library, &path, PLUGIN_INFO_SYMBOL) }?;
        let info = unsafe { info_fn() };
        check_plugin_info(&info)?;
        let boundary_contracts: InstallFn =
            unsafe { symbol(library, &path, BOUNDARY_CONTRACTS_SYMBOL) }?;
        let register: InstallFn = unsafe { symbol(library, &path, REGISTER_SYMBOL) }?;
        Ok(Self {
            path,
            info,
            register,
            boundary_contracts,
        })
    }

    /// Install the plugin (boundary contracts first, then the plugin itself) into `registry`.
    pub fn install_into(&self, registry: &mut PluginRegistry) -> Result<(), PluginLibraryError> {
        call_install(self.boundary_contracts, registry)
            .map_err(|message| PluginLibraryError::BoundaryContractsFailed { message })?;
        call_install(self.register, registry)
            .map_err(|message| PluginLibraryError::RegisterFailed { message })
    }

    /// Metadata reported by the plugin (already verified against the host in `load`).
    pub fn info(&self) -> PluginInfo {
        self.info
    }

    /// ABI version reported by the plugin (equal to [`PLUGIN_ABI_VERSION`] once loaded).
    pub fn abi_version(&self) -> u32 {
        self.info.abi_version
    }

    /// Path the library was loaded from.
    pub fn path(&self) -> &Path {
        &self.path
    }
}

/// # Safety
/// `T` must be the function pointer type matching the exported symbol.
unsafe fn symbol<T: Copy>(
    library: &'static Library,
    path: &Path,
    name: &'static str,
) -> Result<T, PluginLibraryError> {
    // Safety: forwarded from the caller.
    unsafe { library.get::<T>(name.as_bytes()) }
        .map(|sym| *sym)
        .map_err(|_| PluginLibraryError::MissingSymbol {
            path: path.to_path_buf(),
            symbol: name,
        })
}

unsafe extern "C" fn write_error(ctx: *mut c_void, ptr: *const u8, len: usize) {
    if ctx.is_null() || ptr.is_null() {
        return;
    }
    // Safety: `ctx` is the `Option<String>` owned by `call_install`, and the plugin passes a
    // valid `(ptr, len)` byte slice for the duration of this call.
    let (slot, bytes) = unsafe {
        (
            &mut *ctx.cast::<Option<String>>(),
            std::slice::from_raw_parts(ptr, len),
        )
    };
    *slot = Some(String::from_utf8_lossy(bytes).into_owned());
}

fn call_install(install: InstallFn, registry: &mut PluginRegistry) -> Result<(), String> {
    let mut message: Option<String> = None;
    let sink = PluginErrorSink {
        ctx: (&mut message as *mut Option<String>).cast(),
        write: Some(write_error),
    };
    // Safety: the plugin passed the compatibility checks in `load`; the registry pointer is
    // exclusive for the call and `sink` outlives it.
    let ok = unsafe { install(registry as *mut PluginRegistry, sink) };
    if ok {
        Ok(())
    } else {
        Err(message.unwrap_or_else(|| "plugin reported failure without a message".to_string()))
    }
}

fn check_abi_version(found: u32) -> Result<(), PluginLibraryError> {
    check_abi_version_against(found, PLUGIN_ABI_VERSION)
}

/// Verify plugin metadata against this host's Daedalus version, rustc version and build
/// fingerprint.
pub fn check_plugin_info(info: &PluginInfo) -> Result<(), PluginLibraryError> {
    check_plugin_info_against(info, &PluginInfo::for_plugin("host", "host"))
}

fn check_plugin_info_against(
    info: &PluginInfo,
    host: &PluginInfo,
) -> Result<(), PluginLibraryError> {
    check_abi_version_against(info.abi_version, host.abi_version)?;
    let field = |view: StrView, field: &'static str| {
        view.as_str()
            .ok_or(PluginLibraryError::InvalidInfo { field })
    };
    let pair = |f: fn(&PluginInfo) -> StrView, name: &'static str| {
        Ok::<_, PluginLibraryError>((field(f(host), name)?, field(f(info), name)?))
    };
    let (expected, found) = pair(|i| i.daedalus_version, "daedalus_version")?;
    if expected != found {
        return Err(PluginLibraryError::DaedalusVersionMismatch {
            expected: expected.into(),
            found: found.into(),
        });
    }
    let (expected, found) = pair(|i| i.rustc_version, "rustc_version")?;
    if expected != found {
        return Err(PluginLibraryError::RustcVersionMismatch {
            expected: expected.into(),
            found: found.into(),
        });
    }
    let (expected, found) = pair(|i| i.build_fingerprint, "build_fingerprint")?;
    if expected != found {
        return Err(PluginLibraryError::BuildFingerprintMismatch {
            differences: super::describe_fingerprint_mismatch(expected, found),
            expected: expected.into(),
            found: found.into(),
        });
    }
    field(info.plugin_name, "plugin_name")?;
    field(info.plugin_version, "plugin_version")?;
    Ok(())
}

fn check_abi_version_against(found: u32, expected: u32) -> Result<(), PluginLibraryError> {
    if found == expected {
        Ok(())
    } else {
        Err(PluginLibraryError::AbiMismatch { expected, found })
    }
}

/// Find plugin libraries (`.so`, `.dylib`, `.dll`) in `dirs`.
///
/// Directories that do not exist are skipped. When several directories contain a file with
/// the same name, the one from the earliest directory wins. The result is sorted by file name
/// so load order is deterministic.
pub fn discover_plugin_libraries<I, P>(dirs: I) -> std::io::Result<Vec<PathBuf>>
where
    I: IntoIterator<Item = P>,
    P: AsRef<Path>,
{
    let mut found: BTreeMap<std::ffi::OsString, PathBuf> = BTreeMap::new();
    for dir in dirs {
        let entries = match std::fs::read_dir(dir.as_ref()) {
            Ok(entries) => entries,
            Err(err) if err.kind() == std::io::ErrorKind::NotFound => continue,
            Err(err) => return Err(err),
        };
        for entry in entries {
            let path = entry?.path();
            let is_library = path
                .extension()
                .and_then(|ext| ext.to_str())
                .is_some_and(|ext| matches!(ext, "so" | "dylib" | "dll"));
            if !is_library || !path.is_file() {
                continue;
            }
            if let Some(name) = path.file_name() {
                found.entry(name.to_os_string()).or_insert(path);
            }
        }
    }
    Ok(found.into_values().collect())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::dylib::{RUSTC_VERSION, build_fingerprint};

    fn host() -> PluginInfo {
        PluginInfo::for_plugin("host", "0.0.0")
    }

    #[test]
    fn matching_info_is_accepted() {
        let info = PluginInfo::for_plugin("plugin", "1.2.3");
        check_plugin_info(&info).unwrap();
        check_plugin_info_against(&info, &host()).unwrap();
    }

    #[test]
    fn abi_mismatch_is_rejected() {
        let info = PluginInfo {
            abi_version: PLUGIN_ABI_VERSION + 1,
            ..host()
        };
        assert!(matches!(
            check_plugin_info_against(&info, &host()),
            Err(PluginLibraryError::AbiMismatch { expected, found })
                if expected == PLUGIN_ABI_VERSION && found == PLUGIN_ABI_VERSION + 1
        ));
        assert!(matches!(
            check_abi_version(3),
            Err(PluginLibraryError::AbiMismatch { found: 3, .. })
        ));
    }

    #[test]
    fn daedalus_version_mismatch_is_rejected() {
        let info = PluginInfo {
            daedalus_version: StrView::from_static("0.0.1"),
            ..host()
        };
        match check_plugin_info_against(&info, &host()) {
            Err(PluginLibraryError::DaedalusVersionMismatch { expected, found }) => {
                assert_eq!(expected, crate::version());
                assert_eq!(found, "0.0.1");
            }
            other => panic!("unexpected result: {other:?}"),
        }
    }

    #[test]
    fn rustc_version_mismatch_is_rejected() {
        let info = PluginInfo {
            rustc_version: StrView::from_static("rustc 1.0.0 (a59aba2b1 2015-05-13)"),
            ..host()
        };
        match check_plugin_info_against(&info, &host()) {
            Err(PluginLibraryError::RustcVersionMismatch { expected, found }) => {
                assert_eq!(expected, RUSTC_VERSION);
                assert!(found.starts_with("rustc 1.0.0"));
            }
            other => panic!("unexpected result: {other:?}"),
        }
    }

    #[test]
    fn build_fingerprint_mismatch_is_rejected() {
        let plugin_fingerprint: &'static str = Box::leak(
            build_fingerprint()
                .replace("features.runtime=", "features.runtime=gpu,")
                .into_boxed_str(),
        );
        let info = PluginInfo {
            build_fingerprint: StrView::from_static(plugin_fingerprint),
            ..host()
        };
        let err = check_plugin_info_against(&info, &host()).unwrap_err();
        let message = err.to_string();
        match err {
            PluginLibraryError::BuildFingerprintMismatch {
                expected,
                found,
                differences,
            } => {
                assert_eq!(expected, build_fingerprint());
                assert_eq!(found, plugin_fingerprint);
                assert!(
                    differences.starts_with("features.runtime: host `")
                        && differences.contains("plugin `gpu,"),
                    "{differences}"
                );
                assert!(message.contains(&differences));
            }
            other => panic!("unexpected result: {other:?}"),
        }
    }

    #[test]
    fn fingerprint_covers_layout_inputs() {
        let fingerprint = build_fingerprint();
        assert!(fingerprint.contains("features.runtime="));
        assert!(fingerprint.contains(&format!(
            "layout.plugin_registry={}/{}",
            std::mem::size_of::<PluginRegistry>(),
            std::mem::align_of::<PluginRegistry>()
        )));
        assert!(RUSTC_VERSION.starts_with("rustc "));
    }

    #[test]
    fn missing_library_is_a_typed_error() {
        let err = unsafe { PluginLibrary::load("/nonexistent/libdaedalus_missing_plugin.so") }
            .unwrap_err();
        assert!(matches!(err, PluginLibraryError::Load { .. }));
    }

    #[test]
    fn discovery_sorts_and_dedups_by_file_name() {
        let root =
            std::env::temp_dir().join(format!("daedalus-dylib-discovery-{}", std::process::id()));
        let first = root.join("first");
        let second = root.join("second");
        std::fs::create_dir_all(&first).unwrap();
        std::fs::create_dir_all(&second).unwrap();
        for (dir, name) in [
            (&first, "libb.so"),
            (&first, "notes.txt"),
            (&second, "libb.so"),
            (&second, "liba.dylib"),
            (&second, "c.dll"),
        ] {
            std::fs::write(dir.join(name), b"").unwrap();
        }
        let found =
            discover_plugin_libraries([first.clone(), second.clone(), root.join("missing")])
                .unwrap();
        std::fs::remove_dir_all(&root).unwrap();
        assert_eq!(
            found,
            vec![
                second.join("c.dll"),
                second.join("liba.dylib"),
                first.join("libb.so"),
            ]
        );
    }
}
