//! Exercises the symbols generated by `export_plugin!` in-process (no dlopen), including the
//! `boundary_contracts [...]` arm and error reporting through `PluginErrorSink`.

use std::ffi::c_void;

use daedalus::runtime::plugins::{PluginInstallContext, PluginRegistry, PluginResult};
use daedalus::transport::{BoundaryCapabilities, BoundaryTypeContract};
use daedalus::{PLUGIN_ABI_VERSION, Plugin, PluginErrorSink};

#[derive(Default)]
struct DemoPlugin;

impl Plugin for DemoPlugin {
    fn id(&self) -> &'static str {
        "dylib_demo"
    }

    fn install(&self, _ctx: &mut PluginInstallContext<'_>) -> PluginResult<()> {
        Ok(())
    }
}

fn demo_contract() -> BoundaryTypeContract {
    BoundaryTypeContract::for_type::<u64>("dylib_demo:u64", BoundaryCapabilities::default())
}

daedalus::export_plugin!(DemoPlugin, boundary_contracts[demo_contract()]);

unsafe extern "C" fn capture(ctx: *mut c_void, ptr: *const u8, len: usize) {
    let slot = unsafe { &mut *ctx.cast::<Option<String>>() };
    let bytes = unsafe { std::slice::from_raw_parts(ptr, len) };
    *slot = Some(String::from_utf8_lossy(bytes).into_owned());
}

fn sink(slot: &mut Option<String>) -> PluginErrorSink {
    PluginErrorSink {
        ctx: (slot as *mut Option<String>).cast(),
        write: Some(capture),
    }
}

#[test]
fn exported_symbols_report_info_and_install() {
    assert_eq!(daedalus_plugin_abi_version(), PLUGIN_ABI_VERSION);
    let info = daedalus_plugin_info();
    assert_eq!(info.plugin_name.as_str(), Some(env!("CARGO_PKG_NAME")));
    assert_eq!(info.daedalus_version.as_str(), Some(daedalus::version()));
    assert_eq!(
        info.build_fingerprint.as_str(),
        Some(daedalus::build_fingerprint())
    );

    let mut registry = PluginRegistry::new();
    let mut message = None;
    assert!(unsafe {
        daedalus_plugin_register_boundary_contracts(&mut registry, sink(&mut message))
    });
    assert!(unsafe { daedalus_plugin_register(&mut registry, sink(&mut message)) });
    assert_eq!(message, None);
    assert!(
        registry
            .boundary_contracts
            .keys()
            .any(|key| key.to_string() == "dylib_demo:u64")
    );
    assert!(registry.plugin_manifests.contains_key("dylib_demo"));
}

#[test]
fn null_registry_is_reported_not_dereferenced() {
    let mut message = None;
    assert!(!unsafe { daedalus_plugin_register(std::ptr::null_mut(), sink(&mut message)) });
    assert!(message.unwrap().contains("null"));
    assert!(!unsafe {
        daedalus_plugin_register_boundary_contracts(
            std::ptr::null_mut(),
            PluginErrorSink::discard(),
        )
    });
}
