//! Exercises the descriptor generated by `export_plugin!` in-process (no dlopen), including the
//! `boundary_contracts [...]` arm and error reporting through `StrSink`.

use std::ffi::c_void;

use daedalus::runtime::plugins::{PluginInstallContext, PluginResult};
use daedalus::transport::{BoundaryCapabilities, BoundaryTypeContract};
use daedalus::{PLUGIN_ABI_VERSION, Plugin, PluginRegistry, PluginSchema, StrSink};

#[derive(Default)]
struct DemoPlugin;

impl Plugin for DemoPlugin {
    fn id(&self) -> &'static str {
        "dylib_demo"
    }

    fn install(&self, _ctx: &mut PluginInstallContext<'_>) -> PluginResult<()> {
        Ok(())
    }
}

fn demo_contract() -> BoundaryTypeContract {
    BoundaryTypeContract::for_type::<u64>("dylib_demo:u64", BoundaryCapabilities::default())
}

daedalus::export_plugin!(DemoPlugin, boundary_contracts[demo_contract()]);

unsafe extern "C" fn capture(ctx: *mut c_void, ptr: *const u8, len: usize) {
    let slot = unsafe { &mut *ctx.cast::<Option<String>>() };
    let bytes = unsafe { std::slice::from_raw_parts(ptr, len) };
    *slot = Some(String::from_utf8_lossy(bytes).into_owned());
}

fn sink(slot: &mut Option<String>) -> StrSink {
    StrSink {
        ctx: (slot as *mut Option<String>).cast(),
        write: Some(capture),
    }
}

#[test]
fn exported_descriptor_reports_info_schema_and_installs() {
    assert_eq!(daedalus_plugin_abi_version(), PLUGIN_ABI_VERSION);
    let descriptor = daedalus_plugin_descriptor();
    let info = descriptor.info;
    assert_eq!(info.plugin_name.as_str(), Some(env!("CARGO_PKG_NAME")));
    assert_eq!(info.daedalus_version.as_str(), Some(daedalus::version()));
    assert_eq!(
        info.build_fingerprint.as_str(),
        Some(daedalus::build_fingerprint())
    );

    let mut json = None;
    assert!(unsafe { (descriptor.schema)(sink(&mut json)) });
    let schema: PluginSchema = serde_json::from_str(&json.unwrap()).unwrap();
    assert_eq!(schema.plugin.name, "dylib_demo");
    assert!(schema.nodes.is_empty());

    let mut registry = PluginRegistry::new();
    let registry_ptr = (&mut registry as *mut PluginRegistry).cast::<c_void>();
    let mut message = None;
    assert!(unsafe { (descriptor.register_boundary_contracts)(registry_ptr, sink(&mut message)) });
    assert!(unsafe { (descriptor.register)(registry_ptr, sink(&mut message)) });
    assert_eq!(message, None);
    assert!(
        registry
            .boundary_contracts
            .keys()
            .any(|key| *key == "dylib_demo:u64")
    );
    assert!(registry.plugin_manifests.contains_key("dylib_demo"));
}

#[test]
fn null_registry_is_reported_not_dereferenced() {
    let descriptor = daedalus_plugin_descriptor();
    for install in [descriptor.register, descriptor.register_boundary_contracts] {
        let mut message = None;
        assert!(!unsafe { install(std::ptr::null_mut(), sink(&mut message)) });
        assert!(message.unwrap().contains("null"));
    }
}
