use crate::NodeError;
use crate::io::NodeIo;
use daedalus_data::model::Value;
use std::sync::OnceLock;

pub const ENV_NODE_PERF_COUNTERS: &str = "DAEDALUS_NODE_PERF_COUNTERS";
pub const ENV_NODE_CPU_TIME: &str = "DAEDALUS_NODE_CPU_TIME";
pub const ENV_RUNTIME_POOL_SIZE: &str = "DAEDALUS_RUNTIME_POOL_SIZE";

/// Policy for invalid configuration values.
///
/// ```
/// use daedalus_runtime::config::ConfigPolicy;
/// let policy = ConfigPolicy::Clamp;
/// assert_eq!(policy, ConfigPolicy::Clamp);
/// ```
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ConfigPolicy {
    Clamp,
    Error,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct RuntimeDebugConfig {
    pub node_perf_counters: bool,
    pub node_cpu_time: bool,
    pub pool_size: Option<usize>,
}

impl RuntimeDebugConfig {
    pub fn from_env() -> Self {
        Self::from_lookup(|name| std::env::var(name).ok())
    }

    pub fn from_lookup(mut get: impl FnMut(&str) -> Option<String>) -> Self {
        Self {
            node_perf_counters: env_bool(&mut get, ENV_NODE_PERF_COUNTERS),
            node_cpu_time: env_bool(&mut get, ENV_NODE_CPU_TIME),
            pool_size: env_usize(&mut get, ENV_RUNTIME_POOL_SIZE),
        }
    }
}

pub fn runtime_debug_config() -> &'static RuntimeDebugConfig {
    static CONFIG: OnceLock<RuntimeDebugConfig> = OnceLock::new();
    CONFIG.get_or_init(RuntimeDebugConfig::from_env)
}

fn env_bool(get: &mut impl FnMut(&str) -> Option<String>, name: &str) -> bool {
    get(name)
        .map(|value| {
            matches!(
                value.trim().to_ascii_lowercase().as_str(),
                "1" | "true" | "yes" | "on"
            )
        })
        .unwrap_or(false)
}

fn env_usize(get: &mut impl FnMut(&str) -> Option<String>, name: &str) -> Option<usize> {
    get(name)
        .and_then(|value| value.trim().parse::<usize>().ok())
        .filter(|value| *value > 0)
}

/// Record of a configuration value change after sanitization.
///
/// ```
/// use daedalus_runtime::config::{ConfigChange, ConfigPolicy};
/// use daedalus_data::model::Value;
/// let change = ConfigChange {
///     port: "threshold",
///     previous: Value::Int(0),
///     next: Value::Int(1),
///     policy: ConfigPolicy::Clamp,
/// };
/// assert_eq!(change.port, "threshold");
/// ```
#[derive(Debug, Clone, PartialEq)]
pub struct ConfigChange {
    pub port: &'static str,
    pub previous: Value,
    pub next: Value,
    pub policy: ConfigPolicy,
}

/// Sanitized configuration plus any changes applied.
///
/// ```
/// use daedalus_runtime::config::Sanitized;
/// let sanitized = Sanitized { value: 3u8, changes: vec![] };
/// assert_eq!(sanitized.value, 3);
/// ```
#[derive(Debug, Clone, PartialEq)]
pub struct Sanitized<T> {
    pub value: T,
    pub changes: Vec<ConfigChange>,
}

/// Error returned from config validation or sanitization.
///
/// ```
/// use daedalus_runtime::config::ConfigError;
/// let err = ConfigError::for_port("radius", "too small");
/// assert_eq!(err.port, Some("radius"));
/// ```
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ConfigError {
    pub port: Option<&'static str>,
    pub message: String,
}

impl ConfigError {
    /// Create a new config error with no port context.
    pub fn new(message: impl Into<String>) -> Self {
        Self {
            port: None,
            message: message.into(),
        }
    }

    /// Create a new config error scoped to a specific port.
    pub fn for_port(port: &'static str, message: impl Into<String>) -> Self {
        Self {
            port: Some(port),
            message: message.into(),
        }
    }
}

impl std::fmt::Display for ConfigError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        if let Some(port) = self.port {
            write!(f, "{port}: {}", self.message)
        } else {
            write!(f, "{}", self.message)
        }
    }
}

impl std::error::Error for ConfigError {}

/// Trait implemented by config structs generated by `#[derive(NodeConfig)]`.
///
/// ```
/// use daedalus_runtime::config::{ConfigError, NodeConfig, Sanitized};
/// use daedalus_runtime::{NodeError};
/// use daedalus_runtime::io::NodeIo;
///
/// #[derive(Default)]
/// struct DemoConfig {
///     threshold: i64,
/// }
///
/// impl NodeConfig for DemoConfig {
///     fn ports() -> Vec<daedalus_registry::capability::PortDecl> { vec![] }
///     fn from_io(_io: &NodeIo) -> Result<Self, NodeError> { Ok(DemoConfig::default()) }
///     fn sanitize(self) -> Result<Sanitized<Self>, ConfigError> { Ok(Sanitized { value: self, changes: vec![] }) }
///     fn validate(&self) -> Result<(), ConfigError> { Ok(()) }
/// }
///
/// let cfg = DemoConfig::default();
/// cfg.validate().unwrap();
/// ```
pub trait NodeConfig: Sized {
    fn ports() -> Vec<daedalus_registry::capability::PortDecl>;
    fn metadata() -> std::collections::BTreeMap<String, Value> {
        std::collections::BTreeMap::new()
    }
    fn from_io(io: &NodeIo) -> Result<Self, NodeError>;
    fn sanitize(self) -> Result<Sanitized<Self>, ConfigError>;
    fn validate(&self) -> Result<(), ConfigError>;
}

/// Emit warnings for config changes applied by sanitization.
///
/// ```
/// use daedalus_runtime::config::{ConfigChange, ConfigPolicy, log_config_changes};
/// use daedalus_data::model::Value;
/// let changes = vec![ConfigChange {
///     port: "value",
///     previous: Value::Int(0),
///     next: Value::Int(1),
///     policy: ConfigPolicy::Clamp,
/// }];
/// log_config_changes("node", &changes);
/// ```
pub fn log_config_changes(node_id: &str, changes: &[ConfigChange]) {
    for change in changes {
        tracing::warn!(
            "node={} port={} policy={:?} previous={:?} next={:?}",
            node_id,
            change.port,
            change.policy,
            change.previous,
            change.next
        );
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeMap;

    #[test]
    fn runtime_debug_config_parses_known_env_keys() {
        let values = BTreeMap::from([
            (ENV_NODE_PERF_COUNTERS.to_string(), "true".to_string()),
            (ENV_NODE_CPU_TIME.to_string(), "1".to_string()),
            (ENV_RUNTIME_POOL_SIZE.to_string(), "8".to_string()),
        ]);

        let config = RuntimeDebugConfig::from_lookup(|name| values.get(name).cloned());

        assert!(config.node_perf_counters);
        assert!(config.node_cpu_time);
        assert_eq!(config.pool_size, Some(8));
    }

    #[test]
    fn runtime_debug_config_keeps_invalid_values_disabled() {
        let values = BTreeMap::from([
            (ENV_NODE_PERF_COUNTERS.to_string(), "no".to_string()),
            (ENV_NODE_CPU_TIME.to_string(), "definitely".to_string()),
            (ENV_RUNTIME_POOL_SIZE.to_string(), "0".to_string()),
        ]);

        let config = RuntimeDebugConfig::from_lookup(|name| values.get(name).cloned());

        assert!(!config.node_perf_counters);
        assert!(!config.node_cpu_time);
        assert_eq!(config.pool_size, None);
    }
}
