use crate::NodeError;
use crate::io::NodeIo;
use daedalus_data::model::Value;

/// Policy for invalid configuration values.
///
/// ```
/// use daedalus_runtime::config::ConfigPolicy;
/// let policy = ConfigPolicy::Clamp;
/// assert_eq!(policy, ConfigPolicy::Clamp);
/// ```
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ConfigPolicy {
    Clamp,
    Error,
}

/// Record of a configuration value change after sanitization.
///
/// ```
/// use daedalus_runtime::config::{ConfigChange, ConfigPolicy};
/// use daedalus_data::model::Value;
/// let change = ConfigChange {
///     port: "threshold",
///     previous: Value::Int(0),
///     next: Value::Int(1),
///     policy: ConfigPolicy::Clamp,
/// };
/// assert_eq!(change.port, "threshold");
/// ```
#[derive(Debug, Clone, PartialEq)]
pub struct ConfigChange {
    pub port: &'static str,
    pub previous: Value,
    pub next: Value,
    pub policy: ConfigPolicy,
}

/// Sanitized configuration plus any changes applied.
///
/// ```
/// use daedalus_runtime::config::Sanitized;
/// let sanitized = Sanitized { value: 3u8, changes: vec![] };
/// assert_eq!(sanitized.value, 3);
/// ```
#[derive(Debug, Clone, PartialEq)]
pub struct Sanitized<T> {
    pub value: T,
    pub changes: Vec<ConfigChange>,
}

/// Error returned from config validation or sanitization.
///
/// ```
/// use daedalus_runtime::config::ConfigError;
/// let err = ConfigError::for_port("radius", "too small");
/// assert_eq!(err.port, Some("radius"));
/// ```
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ConfigError {
    pub port: Option<&'static str>,
    pub message: String,
}

impl ConfigError {
    /// Create a new config error with no port context.
    pub fn new(message: impl Into<String>) -> Self {
        Self {
            port: None,
            message: message.into(),
        }
    }

    /// Create a new config error scoped to a specific port.
    pub fn for_port(port: &'static str, message: impl Into<String>) -> Self {
        Self {
            port: Some(port),
            message: message.into(),
        }
    }
}

impl std::fmt::Display for ConfigError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        if let Some(port) = self.port {
            write!(f, "{port}: {}", self.message)
        } else {
            write!(f, "{}", self.message)
        }
    }
}

impl std::error::Error for ConfigError {}

/// Trait implemented by config structs generated by `#[derive(NodeConfig)]`.
///
/// ```
/// use daedalus_runtime::config::{ConfigError, NodeConfig, Sanitized};
/// use daedalus_runtime::{NodeError};
/// use daedalus_runtime::io::NodeIo;
///
/// #[derive(Default)]
/// struct DemoConfig {
///     threshold: i64,
/// }
///
/// impl NodeConfig for DemoConfig {
///     fn ports() -> Vec<daedalus_registry::store::Port> { vec![] }
///     fn from_io(_io: &NodeIo) -> Result<Self, NodeError> { Ok(DemoConfig::default()) }
///     fn sanitize(self) -> Result<Sanitized<Self>, ConfigError> { Ok(Sanitized { value: self, changes: vec![] }) }
///     fn validate(&self) -> Result<(), ConfigError> { Ok(()) }
/// }
///
/// let cfg = DemoConfig::default();
/// cfg.validate().unwrap();
/// ```
pub trait NodeConfig: Sized {
    fn ports() -> Vec<daedalus_registry::store::Port>;
    fn metadata() -> std::collections::BTreeMap<String, Value> {
        std::collections::BTreeMap::new()
    }
    fn from_io(io: &NodeIo) -> Result<Self, NodeError>;
    fn sanitize(self) -> Result<Sanitized<Self>, ConfigError>;
    fn validate(&self) -> Result<(), ConfigError>;
}

/// Emit warnings for config changes applied by sanitization.
///
/// ```
/// use daedalus_runtime::config::{ConfigChange, ConfigPolicy, log_config_changes};
/// use daedalus_data::model::Value;
/// let changes = vec![ConfigChange {
///     port: "value",
///     previous: Value::Int(0),
///     next: Value::Int(1),
///     policy: ConfigPolicy::Clamp,
/// }];
/// log_config_changes("node", &changes);
/// ```
pub fn log_config_changes(node_id: &str, changes: &[ConfigChange]) {
    for change in changes {
        log::warn!(
            "node={} port={} policy={:?} previous={:?} next={:?}",
            node_id,
            change.port,
            change.policy,
            change.previous,
            change.next
        );
    }
}
